// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdIhtm34HY3pdmCllehjYPKL5F3d1e6gE',
    appId: '1:7867430804:web:461636ee030e7a29968181',
    messagingSenderId: '7867430804',
    projectId: 'possibilico',
    authDomain: 'possibilico.firebaseapp.com',
    storageBucket: 'possibilico.appspot.com',
    measurementId: 'G-YX65RENDBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MUl5d4_iKozbVYAdDtnpVP1c8SonlAE',
    appId: '1:7867430804:android:b998d9fca120c7d6968181',
    messagingSenderId: '7867430804',
    projectId: 'possibilico',
    storageBucket: 'possibilico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHf2CdZZOrns9FAIq2DmIVrksTDFCoLDA',
    appId: '1:7867430804:ios:0b951868592cd59d968181',
    messagingSenderId: '7867430804',
    projectId: 'possibilico',
    storageBucket: 'possibilico.appspot.com',
    iosClientId: '7867430804-dhpblm6b9idhdg4ho2l6cvgs8glusiig.apps.googleusercontent.com',
    iosBundleId: 'com.example.possibilico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHf2CdZZOrns9FAIq2DmIVrksTDFCoLDA',
    appId: '1:7867430804:ios:0b951868592cd59d968181',
    messagingSenderId: '7867430804',
    projectId: 'possibilico',
    storageBucket: 'possibilico.appspot.com',
    iosClientId: '7867430804-dhpblm6b9idhdg4ho2l6cvgs8glusiig.apps.googleusercontent.com',
    iosBundleId: 'com.example.possibilico',
  );
}
